[package]
name = "smithay-client-toolkit"
version = "0.2.6"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."

[badges]
travis-ci = { repository = "smithay/client-toolkit" }

[dependencies]
bitflags = "1.0"
nix = "0.11"
dlib = "0.4"
lazy_static = "1"
memmap = "0.6"
tempfile = "3.0"
chan = "0.1.21"
wayland-commons = { version = "0.20.7" }
wayland-client = { version = "0.20.7", features = ["cursor"] }
wayland-protocols = { version = "0.20.7", features = ["client", "unstable_protocols"] }

[dev-dependencies]
image = "0.19"
wayland-client = { version = "0.20.7", features = ["dlopen"] }
byteorder = "1.0"
