[package]
name = "smithay-client-toolkit"
version = "0.4.4"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."

[badges]
travis-ci = { repository = "smithay/client-toolkit" }

[dependencies]
bitflags = "1.0"
nix = "0.13"
dlib = "0.4"
lazy_static = "1"
memmap = "0.7"
andrew = "0.2.0"
wayland-commons = { version = "0.22" }
wayland-client = { version = "0.22", features = ["cursor"] }
wayland-protocols = { version = "0.22", features = ["native_client", "unstable_protocols"] }

[dev-dependencies]
image = "0.20"
wayland-client = { version = "0.22", features = ["dlopen"] }
byteorder = "1.0"
