[package]
name = "smithay-client-toolkit"
version = "0.15.3"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
edition = "2018"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."
readme = "README.md"

[dependencies]
bitflags = "1.0"
nix = "0.23.0"
dlib = "0.5"
lazy_static = "1.0"
memmap2 = "0.3.0"
log = "0.4"
thiserror = "1.0.30"
wayland-backend = "0.1.0-alpha1"
wayland-client = "0.30.0-alpha1"
wayland-protocols = { version = "0.30.0-alpha1", features = ["client", "unstable_protocols"] }
wayland-cursor = "0.30.0-alpha1"
calloop = { version = "0.9.1", optional = true }

[features]
default = ["calloop", "system"]
system = ["wayland-backend/client_system"]
dlopen = ["wayland-backend/client_system", "wayland-backend/dlopen"]

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
image = "0.23"
env_logger = "0.9.0"
