[package]
name = "smithay-client-toolkit"
version = "0.16.0"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
edition = "2021"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."
readme = "README.md"

[package.metadata.docs.rs]
features = ["calloop", "xkbcommon"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitflags = "1.0"
nix = { version = "0.25", default-features = false, features = ["fs", "mman"] }
dlib = "0.5"
lazy_static = "1.0"
memmap2 = "0.5.0"
log = "0.4"
thiserror = "1.0.30"
# wayland-backend = "=0.1.0-beta.14"
# wayland-client = "=0.30.0-beta.14"
# wayland-protocols = { version = "=0.30.0-beta.14", features = ["client", "unstable"] }
# wayland-protocols-wlr = { version = "=0.1.0-beta.14", features = ["client"] }
# wayland-cursor = "=0.30.0-beta.14"
# wayland-scanner = "=0.30.0-beta.14"
wayland-backend = { git = "https://github.com/ids1024/wayland-rs", branch = "ext-screencopy" }
wayland-client = { git = "https://github.com/ids1024/wayland-rs", branch = "ext-screencopy" }
wayland-protocols = { git = "https://github.com/ids1024/wayland-rs", branch = "ext-screencopy", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { git = "https://github.com/ids1024/wayland-rs", branch = "ext-screencopy", features = ["client"] }
wayland-cursor = { git = "https://github.com/ids1024/wayland-rs", branch = "ext-screencopy" }
wayland-scanner = { git = "https://github.com/ids1024/wayland-rs", branch = "ext-screencopy" }

xkbcommon = { version = "0.5", optional = true, features = ["wayland"] }
calloop = { version = "0.10.0", optional = true }

[features]
default = ["calloop", "xkbcommon"]

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
image = "0.23"
env_logger = "0.9"
wgpu = "0.13.1"
raw-window-handle = "0.4.3"
pollster = "0.2.5"

[[example]]
name = "wgpu"
required-features = ["wayland-backend/client_system"]
