[package]
name = "smithay-client-toolkit"
version = "0.17.0"
authors = ["Elinor Berger <elinor@safaradeg.net>", "i509VCB <mail@i509.me>", "Ashley Wulber <ashley@system76.com>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
edition = "2021"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."
readme = "README.md"

[package.metadata.docs.rs]
features = ["calloop", "xkbcommon"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitflags = "1.0"
cursor-icon = "1.0.0"
dlib = "0.5"
log = "0.4"
memmap2 = "0.7.0"
nix = { version = "0.26.1", default-features = false, features = ["fs", "mman"] }
thiserror = "1.0.30"
wayland-backend = "0.1.0"
wayland-client = "0.30.2"
wayland-cursor = "0.30.0"
wayland-protocols = { version = "0.30.1", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.1.0", features = ["client"] }
wayland-scanner = "0.30.0"
wayland-csd-frame = { version = "0.2.2", default-features = false, features = ["wayland-backend_0_1"] }

xkbcommon = { version = "0.5.0", optional = true, features = ["wayland"], git = "https://github.com/notgull/xkbcommon-rs.git", branch = "xkeysym" }
calloop = { version = "0.10.5", optional = true }
xkeysym = { git = "https://github.com/notgull/xkeysym.git", version = "0.1.1" }

[features]
default = ["calloop", "xkbcommon"]
calloop = ["dep:calloop", "wayland-client/calloop"]
xkbcommon = ["dep:xkbcommon", "pkg-config"]

[build-dependencies]
pkg-config = { version = "0.3", optional = true }

[dev-dependencies]
bytemuck = "1.13.0"
font-kit = "0.11.0"
image = "0.23"
env_logger = "0.9"
wgpu = "0.15.0"
raqote = "0.8.2"
raw-window-handle = "0.5.2"
pollster = "0.2.5"

[[example]]
name = "wgpu"
required-features = ["wayland-backend/client_system"]
