[package]
name = "smithay-client-toolkit"
version = "0.12.3"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
edition = "2018"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."
readme = "README.md"

[dependencies]
bitflags = "1.0"
nix = "0.18"
dlib = "0.4"
lazy_static = "1.0"
memmap2 = "0.1.0"
andrew = { version = "0.3.0", optional = true }
log = "0.4"
wayland-client = "0.28"
wayland-protocols = { version = "0.28" , features = ["client", "unstable_protocols"] }
wayland-cursor = "0.28"
calloop = { version = "0.6.1", optional = true }

[features]
default = ["frames", "calloop"]
frames = ["andrew"]

[dev-dependencies]
image = "0.23"
